
services:
  db:
    image: mysql:8.0
    container_name: "db_cont"
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: test_db
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports: 
      - "3306:3306"
    volumes:
      - ./data/mysql/db:/var/lib/mysql
    networks:
      - notes-app-nw
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10
      start_period: 90s
  django_app:
    build: .
    container_name: django_app
    restart: always
    depends_on:
      db:
        condition: service_healthy
    environment:
      MYSQL_DATABASE: notesdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_HOST: db
      MYSQL_PORT: 3306
    command: sh -c "python manage.py migrate --noinput && gunicorn notesapp.wsgi:application --bind 0.0.0.0:8000"
    ports:
      - "8000:8000"
    networks:
      - notes-app-nw

  nginx:
    build: ./nginx
    container_name: nginx_cont
    restart: always
    depends_on:
      - django_app
    ports:
      - "80:80"
    networks:
      - notes-app-nw

networks:
  notes-app-nw:

      
